name: Trivial reusable test
on:
  workflow_call:
    inputs:
      project_title:
        required: false
        type: string
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "project_title=${{ inputs.project_title }}"
